### PR TITLE
Fix various bugs in of_substring

### LINKED ISSUE #56: bogus of_substring on "0"
```
# Int32.of_substring "0  " ~pos:0;;
Exception: Invalid_argument "int32.of_substring".
Raised at file "stdlib.ml", line 34, characters 25-45
Called from file "lib/str_conv.ml", line 60, characters 17-24
Called from file "lib/str_conv.ml", line 103, characters 6-41
Called from file "toplevel/toploop.ml", line 180, characters 17-56
```

I'm on it, also improving tests

### PR DESCRIPTION
**Pull request by rixed**
- pos > 0 was not properly handled
- some invalid prefixes were accepted
- digits outside of base or overflow in the trailer was not properly handled

This fix and add tests for all these.

Closes #56

(Note: compared to #57: rebased

### CODE REVIEW

**Comment by rixed** [comment]
By the way, what `int` do we want returned by the of_substring functions ? The position of the first non-digit or the number of consumed characters? Currently it returns the position but I'm afraid this might not be consistent with expectations. WDYT?

**Comment by rgrinberg** [comment]
The number of consumed characters seems like a more useful return value to me.

**Comment by rixed** [comment]
I propose to change that in a follow-up PR if others agree.

**Comment by rgrinberg** [comment]
LGTM.

**Pull request merged**
